from filters_opencv.filters.global_filters.medium_filters.averaging_color import average_color
from filters_opencv.filters.global_filters.medium_filters.darkening import darken
from filters_opencv.filters.global_filters.medium_filters.lightening import lighten
