from filters_opencv.filters.local_filters.border_selection.sobel import sobel
from filters_opencv.filters.local_filters.border_selection.pruitt import pruitt
from filters_opencv.filters.local_filters.border_selection.sharra import sharra