from filters_opencv.filters.global_filters.medium_filters import average_color, darken, lighten
from filters_opencv.filters.global_filters.linear_stretch import linear_stretch
from filters_opencv.filters.global_filters.embossing import embossing
from filters_opencv.filters.global_filters.rainbow_border import rainbow_border